# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from .bao_cao_doanh_so_ban_san_pham import bao_cao_doanh_so_ban_san_pham
from .report_customer_deposit import report
from .bao_cao_doanh_so_ban_dich_vu import bao_cao_doanh_so_ban_dich_vu
from .bao_cao_doanh_thu_thuc_hien_dich_vu import bao_cao_doanh_thu_thuc_hien_dich_vu
from .bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh import bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh
from .bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham import bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham
from .bao_cao_doanh_thu_tru_bao_hanh import bao_cao_doanh_thu_tru_bao_hanh
from .bao_cao_sale_marketing_lead_da import bao_cao_co_hoi
from .bao_cao_sale_marketing_booking_da import bao_cao_booking_da
from .bao_cao_sale_marketing_so_da import bao_cao_sale_order
from .bao_cao_sale_marketing_walkin_da import bao_cao_sale_marketing_walkin_da
from .bao_cao_doanh_thu_benh_nhan_luu import bao_cao_doanh_thu_benh_nhan_luu
from .bao_cao_doanh_thu_cshp import bao_cao_doanh_thu_cshp
from .bao_cao_khach_hang_dac_biet import bao_cao_khach_hang_dac_biet
from .bao_cao_giam_gia_sau import bao_cao_giam_gia_sau
from .bao_cao_sale_marketing_payment_da import bao_cao_payment
# from .bao_cao_doanh_so_ngay import daily_sales_report
from .bao_cao_doanh_so_ngay_v2 import report_erp_sale_daily
from .bao_cao_doanh_thu import report_revenue_patient
from .bao_cao_marketing_booking import bao_cao_booking
from .bao_cao_ke_toan_doanh_thu_thuc_hien_toan_bo_dich_vu import bao_cao_ke_toan_doanh_thu_thuc_hien_dich_vu
from .bao_cao_so_luong_khach_hang import bao_cao_so_luong_khach_hang
from .bao_cao_doanh_thu_thuc_hien_dich_vu_kangnam import bao_cao_doanh_thu_thuc_hien_dich_vu
from .bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh_kangnam import bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh
from .bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham_kangnam import bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham
from .bao_cao_doanh_thu_ban_dich_vu_cho_khach_bao_hanh_kangnam import bao_cao_doanh_thu_thuc_hien_dich_vu
from .bao_cao_doanh_thu_ban_dich_vu_kangnam import bao_cao_doanh_thu_ban_dich_vu
from .mau_kpi_bao_cao_doanh_thu_ban_dich_vu_kangnam import bao_cao_doanh_thu_ban_dich_vu
from .bao_cao_doanh_thu_thuc_hien_dich_vu_kangnam_kpi import bao_cao_doanh_thu_thuc_hien_dich_vu
from .mau_kpi_bao_cao_doanh_so_ban_san_pham_cua_kangnam import bao_cao_doanh_thu_ban_dich_vu
from .mau_kpi_bao_cao_doanh_so_dich_vu_tham_my_kangnam_cho_khach_bao_hanh import bao_cao_doanh_thu_thuc_hien_dich_vu
from .bao_cao_huy_dong_dich_vu import huy_dong_dich_vu
from .bao_cao_hoan_tien import bao_cao_hoan_tien
from . import theme_report
from . import paris
from .ke_toan_doanh_so_hang_thang import ke_toan_doanh_so_hang_thang
from .bao_cao_doanh_so_ban_san_pham_dich_vu import bao_cao_doanh_so_san_pham_dich_vu
from .bao_cao_khach_hang_tai_kham import bao_cao_khach_hang_tai_kham
from .bao_cao_chi_tiet_doanh_so_DA import bao_cao_chi_tiet_doanh_so_DA
from . import ehc
from .bao_cao_phone_call import bao_cao_phone_call
