from .bao_cao_chi_tiet_doanh_so import crm_sale_payment_detail_report
from .bao_cao_chi_tiet_doanh_so_dich_vu import crm_sale_payment_service_report
from .bao_cao_chi_tiet_doanh_so_ngay import crm_sale_payment_day_report
from .bao_cao_chi_tiet_doanh_so_thang import crm_sale_payment_report
from .ta_bao_cao_doanh_so_theo_nguon_online_offline import online_offline_sales_report
from .ta_bao_cao_doanh_so_theo_nguon import source_sales_report
from .ta_bao_cao_doanh_so_vuot_tran import over_discount_sales_report
from .ta_bao_cao_doanh_so_theo_nguon_sp_dv import source_service_product_sales_report