# -*- coding: utf-8 -*-

{
    'name': 'SCI Accounting',
    'version': '13.0.1.0.0',
    'summary': """Customized accounting for HIS.""",
    'description': '',
    'category': 'Accounting/Accounting',
    'author': 'Nomed',
    'company': 'SCI Group',
    'website': "https://scigroup.com.vn",
    'depends': ['stock_intercompany_transfer', 'account_standard_report', 'stock_account',
                'account',
                # 'account_reports', not use this module in production server
                'shealth_all_in_one', 'sci_brand'],
    'data': ['data/account_data.xml',
             'security/ir.model.access.csv',
             'security/ir.rule.xml',
             'views/stock_valuation_layer_views.xml',
             'views/account_move_line_view.xml',
             # 'views/account_payment_transfer_view.xml',
             # 'views/account_move_form_inherit.xml',
             # 'views/register_payment_behalf.xml',
             # 'views/account_payment_transfer_menu.xml',
             # 'wizard/account_internal_debt_view.xml',
             # 'wizard/register_payment_for_behalf.xml',
             ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'post_init_hook': 'post_init',
    'application': True,
}
