{
    'name': 'Report Sale ERP',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': 'Đoàn Cao Sơn',
    'sequence': '1',
    'summary': 'Report sale ERP',
    'depends': [
        'sale',
        'shealth_all_in_one',
        'sci_hrms'
    ],
    'data': [
        'security/report_ehc_deposit.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/assets.xml',
        'report/phone_call_report.xml',
        'report/phone_call_report_spa.xml',
        'report/phone_call_report_laser.xml',
        'report/phone_call_report_odontology.xml',
        'report/phone_call_report_surgery.xml',
        'wizard/bao_cao_doanh_so_ban_san_pham/bao_cao_doanh_so_ban_san_pham.xml',
        # 'wizard/report_customer_deposit/report.xml',
        'wizard/bao_cao_doanh_so_ban_dich_vu/bao_cao_doanh_so_ban_dich_vu.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu/bao_cao_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh/bao_cao_doanh_thu_thuc_hien_dich_vu_hanh.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham/bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham.xml',
        'wizard/bao_cao_doanh_thu_tru_bao_hanh/bao_cao_doanh_thu_tru_bao_hanh.xml',
        'wizard/bao_cao_sale_marketing_lead_da/bao_cao_co_hoi.xml',
        'wizard/bao_cao_sale_marketing_booking_da/bao_cao_booking_da.xml',
        'wizard/bao_cao_sale_marketing_so_da/bao_cao_sale_order.xml',
        'wizard/bao_cao_sale_marketing_walkin_da/bao_cao_sale_marketing_walkin_da.xml',
        'wizard/bao_cao_sale_marketing_payment_da/bao_cao_payment.xml',
        'wizard/bao_cao_giam_gia_sau/bao_cao_giam_gia_sau.xml',
        'wizard/bao_cao_doanh_thu_benh_nhan_luu/bao_cao_doanh_thu_benh_nhan_luu.xml',
        'wizard/bao_cao_doanh_thu_cshp/bao_cao_doanh_thu_cshp.xml',
        'wizard/bao_cao_khach_hang_dac_biet/bao_cao_khach_hang_dac_biet.xml',
        # 'wizard/bao_cao_doanh_so_ngay/daily_sales_report.xml',
        'wizard/bao_cao_doanh_so_ngay_v2/report_erp_sale_daily.xml',
        'wizard/bao_cao_doanh_thu/report_revenue_patient.xml',
        'wizard/bao_cao_marketing_booking/bao_cao_booking.xml',
        'wizard/bao_cao_ke_toan_doanh_thu_thuc_hien_toan_bo_dich_vu/bao_cao_ke_toan_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_so_luong_khach_hang/bao_cao_so_luong_khach_hang.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_kangnam/bao_cao_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_bao_hanh_kangnam/bao_cao_doanh_thu_thuc_hien_dich_vu_hanh.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham_kangnam/bao_cao_doanh_thu_thuc_hien_dich_vu_tai_kham.xml',
        'wizard/bao_cao_doanh_thu_thuc_hien_dich_vu_kangnam_kpi/bao_cao_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_doanh_thu_ban_dich_vu_cho_khach_bao_hanh_kangnam/bao_cao_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_doanh_thu_ban_dich_vu_kangnam/bao_cao_doanh_thu_ban_dich_vu.xml',
        'wizard/mau_kpi_bao_cao_doanh_thu_ban_dich_vu_kangnam/bao_cao_doanh_thu_ban_dich_vu.xml',
        'wizard/mau_kpi_bao_cao_doanh_so_ban_san_pham_cua_kangnam/bao_cao_doanh_thu_ban_dich_vu.xml',
        'wizard/mau_kpi_bao_cao_doanh_so_dich_vu_tham_my_kangnam_cho_khach_bao_hanh/bao_cao_doanh_thu_thuc_hien_dich_vu.xml',
        'wizard/bao_cao_huy_dong_dich_vu/huy_dong_dich_vu.xml',
        'wizard/bao_cao_hoan_tien/bao_cao_hoan_tien.xml',
        'wizard/paris/c_bao_cao_van_hanh/c_1_bao_cao_cham_soc_khach_hang/bao_cao_cham_soc_lich_cat_chi_kh_phau_thuat/report_paris_phone_call_cham_soc_khach_hang_view.xml',
        'wizard/ke_toan_doanh_so_hang_thang/ke_toan_doanh_so_hang_thang.xml',
        'wizard/bao_cao_doanh_so_ban_san_pham_dich_vu/bao_cao_doanh_so_ban_san_pham.xml',
        'wizard/bao_cao_khach_hang_tai_kham/bao_cao_khach_hang_tai_kham.xml',
        'wizard/bao_cao_chi_tiet_doanh_so_DA/bao_cao_chi_tiet_doanh_so_DA.xml',
        'wizard/ehc/bao_cao_doanh_so_khach_hang_dat_coc/crm_hh_ehc_report_deposit.xml',
        'wizard/bao_cao_phone_call/bao_cao_phone_call.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
