{
    'name': 'Phiếu tư vấn',
    'version': '1.0.0',
    'category': 'Sales',
    'sequence': '3',
    'author': 'SCI_IT',
    'summary': 'Quản lý phiếu tư vấn',
    'depends': [
        'crm_consultation_tickets','sh_intro_service'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/desire_config.xml',
        'data/painpoint_config.xml',
        'data/state_config.xml',
        'views/assets.xml',
        'views/crm_lead.xml',
        'views/crm_line.xml',
        'views/crm_advise_desire.xml',
        'views/crm_advise_painpoint.xml',
        'views/crm_advise_state.xml',
        'views/crm_advise_desire_line.xml',
        'views/crm_advise_painpoint_line.xml',
        'views/crm_advise_state_line.xml',
        'views/crm_advise_line.xml',
        'views/res_partner.xml',
        'views/crm_phone_call.xml',
        'views/menu.xml',
        'wizard/cancel_advise_view.xml',
        'wizard/cancel_advise_potential.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
