{
    'name': 'SCI Notebook Accounting',
    'version': 'Version',
    'summary': 'Summery',
    'description': 'Description',
    'category': 'Category',
    'author': 'hungtn@scigroup.com.vn',
    'website': 'Website',
    'depends': ['portal', 'rating', 'crm_base', 'hr', 'shealth_all_in_one'],
    'data': [
        'security/rule.xml',
        'security/ir.model.access.csv',
        'data/accounting_note.xml',
        'data/data_source_config_account.xml',
        'data/data_source_revenue_config.xml',
        'data/data_item_config.xml',
        'views/sales_by_sources.xml',
        'views/cost_item_config_view.xml',
        'views/source_revenue_config.xml',
        'views/actions_server_view.xml',
        'views/source_config_view.xml',
        'views/plan_revenue_view.xml',
        'views/plan_cost_view.xml',
        'views/sales_by_sources_auto.xml',
        'report/report_by_source.xml',
        'report/report_by_service.xml',
        'report/report_by_revenue.xml',
        'report/report_by_cost.xml',
        'report/report_compare_by_date.xml',
        'wizard/sales_by_source_locked_wizard.xml',
        'wizard/calculator_index_roi_view.xml',
        'wizard/message_wizard.xml',
        'report/dashboard.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
