{
    'name': 'CRM Coupon',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': '',
    'sequence': '10',
    'summary': 'apply coupon to lead/booking',
    'depends': [
        'base',
        'crm',
        'crm_his_13',
        'custom_partner',
        'sale',
        'sale_management',
        'sale_crm',
        'account',
        'stock',
        'sh_message',
        'sci_brand',
        'crm_booking_order',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/crm_group_customer_code.xml',
        'views/group_customer_view.xml',
        'views/crm_booking_view.xml',
        'views/crm_discount_program_view.xml',
        'views/crm_lead.xml',
        # 'views/crm_payment_view.xml',
        'views/crm_request_deposit_view.xml',
        'views/history_discount_view.xml',
        'views/res_company_view.xml',
        'views/sh_medical_ceiling_discount_view.xml',
        # 'views/crm_used_coupon_view.xml',
        'wizard/apply_coupon_view.xml',
        'wizard/new_apply_coupon_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [
        # 'static/src/xml/button_tree.xml'
    ],
}
