from . import labconn_common
from . import get_doctor
from . import get_department
from . import get_labtest
from . import get_test_machine
from . import get_patient_waiting
from . import get_result_lab_test
from . import detail_lab_test
from . import progress_lab_test
