{
    'name': 'CRM HIS 13',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': 'SCI',
    'sequence': '10',
    'summary': 'Custom workflow CRM',
    'depends': [
        'crm_base',
        'shealth_all_in_one',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/default.xml',
        'data/cron.xml',
        'data/paper.xml',
        'views/rule_debt_view.xml',
        'views/crm_debt_review.xml',
        'views/view_crm_line.xml',
        'views/crm_discount_program.xml',
        'views/sale_order.xml',
        'views/payment.xml',
        'views/phone_call.xml',
        'views/crm_report.xml',
        'views/crm_report_template.xml',
        'views/template_kn.xml',
        'views/template_pr.xml',
        'views/case.xml',
        'views/sh_inherit.xml',
        'wizard/view_select_service.xml',
        'wizard/crm_create_guarantee.xml',
        'wizard/apply_disount_program.xml',
        'wizard/crm_program_renewal.xml',
        'wizard/update_uom_price_source.xml',
        'wizard/crm_request_refund.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
