from . import collaborator_account
from . import collaborator_bank
from . import collaborator_bank_config
from . import collaborator_collaborator
from . import collaborator_contract
from . import collaborator_contract_type
from . import collaborator_lead
from . import collaborator_booking
from . import collaborator_payment
from . import collaborator_transaction
from . import crm_lead
from . import res_brand
from . import res_company
from . import sale_order
from . import utm_source
from . import collaborator_service_not_allow
from . import mailmerge
from . import res_partner
from . import sh_inherit
from . import collaborator_overseas_type
from . import account_payment
