{
    'name': 'Cộng tác viên',
    'version': '1.0.0',
    'category': 'Sales',
    'sequence': '3',
    'author': 'SCI_IT',
    'summary': 'Quản lý công tác viên',
    'depends': [
        'crm_his_13',
        # 'crm_base',
        #       'account',
        #       'base',
        'qrcodes',
    ],
    'data': [
        'security/collaborator_security.xml',
        'security/ir.model.access.csv',
        'data/template_collaborator_contract_kn.xml',
        'data/template_collaborator_contract_pa.xml',
        'data/template_collaborator_contract_agency.xml',
        'data/collaborator_bank_config.xml',
        'data/cron_update_collaborators.xml',
        'data/sequence.xml',
        # 'data/account_data.xml',
        # 'views/inherit_account_payment_collaborator_views.xml',

        'views/collaborator_collaborator_views.xml',
        'views/collaborator_templates.xml',
        'views/collaborator_contract_type_views.xml',
        'views/collaborator_overseas_type_views.xml',
        'views/collaborator_contract_views.xml',
        'views/collaborator_bank_views.xml',
        'views/collaborator_bank_config_views.xml',
        'views/collaborator_account_views.xml',
        'views/crm_lead_views.xml',
        'views/res_brand_views.xml',
        'views/res_company_views.xml',
        'views/utm_source_views.xml',
        'views/collaborator_payment.xml',
        # 'views/collaborator_rate_config_views.xml',
        'views/collaborator_service_not_allow_config_view.xml',
        'views/collaborator_transaction_line_views.xml',

        'views/sh_inherit.xml',
        'views/res_partner_views.xml',
        'views/sale_order.xml',

        # 'views/products_discount_views.xml',
        # 'views/collaborator_contract_views.xml',
        # 'views/view_account_payment_collaborator.xml',
        'wizard/create_contract_wizard.xml',
        # 'wizard/bao_cao_chi_tiet_doanh_so/collaborator_report.xml',
        # 'wizard/bao_cao_hoa_hong_cong_tac_vien/collaborator_payment_view_report.xml',
        'wizard/bao_cao/collaborator_report_transaction_wizard_view.xml',
        'wizard/collaborator_create_lead.xml',
        'wizard/collaborator_extend_contract.xml',
        'wizard/collaborator_crm_lead.xml',
        'views/collaborator_menus.xml',

        'wizard/sale_order_wizard.xml',
        'wizard/collaborator_transaction_cancel_wizard.xml',
        'wizard/tool_cancel_payment/tool_cancel_payment_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
