{
    'name': 'CRM Account Analytic',
    'version': '1.0',
    'category': 'Invoice',
    'author': 'Hoang NV',
    'sequence': '11',
    'summary': 'CRM Account Analytic',
    'depends': [
        'crm',
        'crm_base',
        'sale_crm',
        'account',
        'stock',
        'sh_intro_service',
        # 'analytic',
        # 'tas_payment',
    ],
    'data': [
        'views/cost_allocation.xml',
        'views/account_move_views.xml',
        'views/account_analytic_group.xml',
        'views/account_analytic_tag.xml',
        'views/account_account_equivalent.xml',
        'views/account_journal_equivalent.xml',
        'views/budget_view.xml',
        'wizard/account_analytic_group_update_rate_view.xml',
        'wizard/account_analytic_tag_update_rate_view.xml',
        'data/cost_allocation_sequence.xml',
        'data/account_move_sequence.xml',
        'security/ir.model.access.csv',
        'query/delete_translate.sql',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
