{
    'name': 'CRM EHC',
    'version': '13.0.0.0.0',
    'category': 'Sales/CRM',
    'author': 'Đoàn Cao Sơn',
    'sequence': '10',
    'summary': 'Custom workflow CRM EHC',
    'depends': [
        'crm_base', 'base_unit_vn', 'restful', 'utm', 'crm_collaborators', 'crm'
    ],
    'data': [
        'security/security_ehc.xml',
        'security/ir.model.access.csv',
        'data/ir_config_param.xml',
        'data/default_data_faculty.xml',
        'views/crm_hh_ehc_menu_view.xml',
        'views/crm_hh_ehc_department_view.xml',
        'views/crm_hh_ehc_user_view.xml',
        'views/crm_hh_ehc_source_inherit_view.xml',
        # 'views/crm_hh_ehc_group_master_service.xml',
        'views/crm_hh_ehc_inherit_product_category_view.xml',
        'views/crm_hh_ehc_inherit_product_product_view.xml',
        'views/crm_hh_ehc_inherit_product_template_view.xml',
        'views/crm_hh_ehc_booking_view.xml',
        'views/crm_hh_ehc_medical_record.xml',
        'views/crm_hh_ehc_payment_view.xml',
        'views/crm_hh_ehc_crm_line_inherit_view.xml',
        'views/cron.xml',
        'views/address_view.xml',
        'views/crm_hh_ehc_patient_view.xml',
        'views/crm_hh_ehc_service_view.xml',
        'views/crm_hh_ehc_faculty_view.xml',
        'views/crm_hh_ehc_utm_source_ctv_view.xml',
        'views/crm_hh_ehc_account_payment_inherit.xml',
        'views/crm_hh_ehc_inherit_crm_case_view.xml',
        # 'views/crm_hh_ehc_contract_group_exam.xml',
        # 'views/crm_hh_ehc_sale_medicine.xml',
        'views/crm_hh_ehc_utm_source_view.xml',
        'views/crm_hh_ehc_map_utm_source_view.xml',
        'wizard/add_patient_code.xml',
        'wizard/view_allocation.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'qweb': [],
}
