from . import case
from . import crm
from . import crm_debt_review
from . import crm_discount_program
from . import crm_line
from . import payment
from . import phone_call
from . import rule_debt
from . import sale_order
from . import sh_inherit
from . import statement
