from . import crm_hh_ehc_department
from . import crm_hh_ehc_user
from . import crm_hh_ehc_source_inherit
from . import crm_hh_ehc_group_master_service
from . import crm_hh_ehc_product_product
from . import crm_hh_ehc_product_template
from . import crm_hh_ehc_statement_payment
from . import crm_hh_ehc_medical_record
from . import crm_hh_ehc_crm_line_inherit
from . import address
from . import crm_hh_ehc_material_booking
from . import crm_hh_ehc_inherit_crm_lead
from . import patient_ehc
from . import service_ehc
from . import crm_hh_ehc_faculty
from . import crm_hh_ehc_account_payment_inherit
from . import crm_hh_ehc_crm_case_inherit
from . import crm_hh_ehc_contract_group_exam
from . import crm_hh_ehc_sale_medicine
from . import crm_hh_ehc_source
