{
    'name': 'Report CRM',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': 'Đoàn Cao Sơn',
    'sequence': '10',
    'summary': 'Report CRM',
    'depends': [
        'crm_base',
        'crm_coupon',
        'shealth_all_in_one',
    ],
    'data': [
        'security/report_crm.xml',
        'data/ir_config_param.xml',
        'views/report_menu.xml',
        'views/product_pricelist_item_tree_view_inherit.xml',
        'wizard/bao_cao_doanh_so_ngay/daily_sales_report.xml',
        # 'wizard/bao_cao_tong_quan_thuong_hieu/bao_cao_tong_quan_thuong_hieu.xml',
        # 'wizard/bao_cao_doanh_so_theo_nguon/bao_cao_doanh_so_theo_nguon.xml',
        # 'wizard/bao_cao_doanh_so_thuong_hieu_theo_ngay/bao_cao_doanh_so_thuong_hieu_theo_ngay_theo.xml',
        # 'wizard/bao_cao_thong_ke_tuong_tac_theo_nhom_dich_vu/bao_cao_thong_ke_tuong_tac_theo_nhom_dich_vu.xml',
        # 'wizard/bao_thong_ke_tuong_tac_mot_dich_vu_theo_ngay/bao_cao_thong_ke_tuong_tac_mot_dich_vu_theo_ngay.xml',
        # 'wizard/xuat_lead_bk/xuat_lead_bk.xml',
        'wizard/bao_cao_lead_booking/bao_cao_lead_booking.xml',
        # 'wizard/bao_cao_giam_gia_sau/bao_cao_giam_gia_sau.xml',
        'wizard/bao_cao_doanh_so_ngay_v2/report_erp_sale_daily.xml',
        'wizard/bao_cao_tnkh/report_tnkh.xml',
        'wizard/bao_cao_doanh_thu_ban_san_pham/bao_cao_doanh_thu_san_pham.xml',
        'wizard/bao_cao_loc_khach_hang/bao_cao_loc_khach_hang.xml',
        'wizard/bao_cao_the_thanh_vien/report_loyalty_card.xml',
        'wizard/xuat_du_lieu_khach_hang_ma_hoa/xuat_du_lieu_khach_hang_ma_hoa.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
