{
    'name': 'CRM Loyalty',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': 'SCI-IT',
    'sequence': '10',
    'summary': 'Workflow loyalty',
    'depends': [
        'crm_base',
        'queue_job',
        # 'qrcodes',
    ],
    'data': [
        'data/data_loyalty_rank.xml',
        'data/qr_loyalty_card_data.xml',
        'data/data.xml',
        'security/group_loyalty.xml',
        'security/ir.model.access.csv',
        'views/config.xml',
        'views/qr_templates.xml',
        'views/inherit_loyalty.xml',
        'views/rank_view.xml',
        'views/reward_line.xml',
        'views/loyalty_view.xml',
        'views/other_model_view.xml',
        'wizard/view_use_reward_product.xml',
        'wizard/qr_action_view.xml',
        'wizard/scan_loyalty_card_view.xml',
        'wizard/update_code_card.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
