{
    'name': 'CRM Tool',
    'version': '1.0',
    'category': 'Sales/CRM',
    'author': '',
    'sequence': '10',
    'summary': 'Tool cập nhật',
    'depends': [
        'crm_base',
        'loyalty',
        'call_center_cs',
        'shealth_all_in_one'
    ],
    'data': [
        'security/group.xml',
        'wizard/change_phone_view.xml',
        'wizard/partner_change_phone_view.xml',
        'wizard/update_booking.xml',
        'wizard/update_crm_line.xml',
        'wizard/history_phone_call/get_history_phone_call_views.xml',
        'wizard/change_journal.xml',
        'views/crm_lead_view.xml',
        'views/partner_view.xml',
        'views/sale_order.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/loyalty.xml',
        'views/sh_inherit.xml',
        'wizard/update_order_view_wizard.xml',
        'wizard/update_loyalty.xml',
        'wizard/create_negative_so.xml',
        'wizard/update_line_consultants.xml',
        'wizard/create_temp_sms_brand/create_sms_temp.xml',
        'data/cron.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
